# Generated by Django 5.1.1 on 2024-09-23 16:08

from django.db import migrations
from django.contrib.auth.models import Group

def create_operator_group(apps, schema_editor):
    Group.objects.get_or_create(name='Оператор')


class Migration(migrations.Migration):
    dependencies = [
        ('robotbenchmark', '0011_problem_image'),
    ]

    operations = [
        migrations.RunPython(create_operator_group),
    ]
