# Generated by Django 5.1.1 on 2024-09-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotbenchmark', '0012_add_operator_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemuser',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
