# Generated by Django 5.1.1 on 2024-09-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotbenchmark', '0013_problemuser_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
