# Generated by Django 5.1.1 on 2024-09-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotbenchmark', '0014_tournament_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemuser',
            name='grades',
            field=models.JSONField(default=dict),
        ),
    ]
