# Generated by Django 5.1.2 on 2024-11-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotbenchmark', '0015_problemuser_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
