# Generated by Django 5.1.2 on 2024-11-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotbenchmark', '0016_problem_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='problemuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problemuser',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='robotbenchmark.tournament'),
            preserve_default=False,
        ),
    ]
