# Generated by Django 5.1.2 on 2024-11-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotbenchmark', '0017_remove_problem_is_blocked_problemuser_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemuser',
            name='launch_command',
            field=models.TextField(default=''),
        ),
    ]
