# Generated by Django 5.1.2 on 2024-11-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotbenchmark', '0018_problemuser_launch_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemuser',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='problemuser',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='problemuser',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='problemuser',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершена'), ('QUARANTINE', 'В карантине'), ('CHECKED', 'Проверена'), ('REWORK', 'Отправлена на доработку')], default='CREATED'),
        ),
    ]
