# Generated by Django 4.1.3 on 2025-01-03 15:39

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robotbenchmark', '0019_remove_problemuser_is_blocked_and_more'), 
    ]

    operations = [
        migrations.AlterField(
            model_name='commandqueue',
            name='command',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='problem',
            name='world_path',
            field=models.CharField(choices=[('webots_ros2_suv', 'webots_ros2_suv'), ('webots_ros2_tesla', 'webots_ros2_tesla'), ('webots_ros2_control', 'webots_ros2_control'), ('webots_ros2_driver', 'webots_ros2_driver'), ('webots_ros2_epuck', 'webots_ros2_epuck'), ('webots_ros2_importer', 'webots_ros2_importer'), ('webots_ros2_mavic', 'webots_ros2_mavic'), ('webots_ros2_msgs', 'webots_ros2_msgs'), ('webots_ros2_tests', 'webots_ros2_tests'), ('webots_ros2_tiago', 'webots_ros2_tiago'), ('webots_ros2_turtlebot', 'webots_ros2_turtlebot'), ('webots_ros2_universal_robot', 'webots_ros2_universal_robot')], max_length=50),
        ),
        migrations.AlterField(
            model_name='problemuser',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершена'), ('QUARANTINE', 'В карантине'), ('CHECKED', 'Проверена'), ('REWORK', 'Отправлена на доработку')], default='CREATED', max_length=25),
        ),
    ]
