# Generated by Django 4.1.3 on 2025-01-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotbenchmark', '0020_alter_commandqueue_command_alter_problem_world_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
