# Generated by Django 5.1.1 on 2025-01-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotbenchmark', '0021_alter_tournament_date_start_alter_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandqueue',
            name='command_type',
            field=models.CharField(choices=[('os_command', 'OS Command'), ('custom', 'Custom Command')], default='os_command', max_length=20, verbose_name='Тип команды'),
        ),
    ]
