# Generated by Django 5.1.1 on 2025-01-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotbenchmark', '0022_commandqueue_command_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandqueue',
            name='command',
            field=models.CharField(),
        ),
    ]
