# renew_before_expiry = 30 days
version = 3.1.0
archive_dir = /etc/letsencrypt/archive/virtual.robocross.ru
cert = /etc/letsencrypt/live/virtual.robocross.ru/cert.pem
privkey = /etc/letsencrypt/live/virtual.robocross.ru/privkey.pem
chain = /etc/letsencrypt/live/virtual.robocross.ru/chain.pem
fullchain = /etc/letsencrypt/live/virtual.robocross.ru/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = ccdfb1cbbd6e2a34c518e969183ab9bf
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
virtual.robocross.ru = /var/www/certbot
